# diesel.toml

[print_schema.parts]
file = "src/diesel_schema/parts.rs"
filter = { only_tables = ["parts", "manufacturers", "categories", "cpu_specs", "gpu_specs", "memory_specs", "storage_specs"] }

[print_schema.configurations]
file = "src/diesel_schema/configurations.rs"
filter = { only_tables = ["configurations", "configuration_parts"] }

[print_schema.users]
file = "src/diesel_schema/users.rs"
filter = { only_tables = ["users"] }

[migrations_directory]
dir = "migrations"

