name: Deploy Documentation

on:
  push:
    branches: [ deploy-pages ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Rust toolchain
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      # Step 3: Generate documentation
      - name: Generate Documentation
        run: cargo doc --no-deps --document-private-items

      # Step 4: Upload the generated documentation as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./target/doc

      # Step 5: Deploy to GitHub Pages using actions/deploy-pages@v4
      - name: Deploy Documentation to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          publish_branch: gh-pages
          # cname: your.custom.domain.com  # Optional: Uncomment and set if using a custom domain

