name: Deploy Documentation

on:
  push:
    branches: [deploy-pages]  # Ensure this is the correct branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  # Build job
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Rust toolchain
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      # Step 3: Configure cache for dependencies
      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      # Step 4: Clean the docs folder
      - name: Clean Docs Folder
        run: cargo clean --doc

      # Step 5: Generate documentation
      - name: Build Docs
        run: cargo doc --no-deps --document-private-items

      # Step 6: Add a redirect to the docs root
      - name: Add Redirect to Docs Root
        run: echo '<meta http-equiv="refresh" content="0;url=rust_backend/index.html">' > target/doc/index.html

      # Step 7: Remove the .lock file if it exists
      - name: Remove Lock File
        run: rm target/doc/.lock || true

      # Step 8: Upload the generated documentation as an artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc  # Directly upload the docs from target/doc

  # Deploy job
  deploy:
    name: Deploy

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build # Ensure this job depends on 'build' finishing successfully

    steps:
      # Deploy the uploaded artifact to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

