name: Rust Tests with Database

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN: {}  # Ensure the calling workflow passes the GITHUB_TOKEN

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read  # Necessary for actions/checkout

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    env:
      DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db

    steps:
    - name: Checkout Rust repository
      uses: actions/checkout@v3
      with:
        repository: BlakeDonn/trustystack-rust
        ref: ${{ github.ref }}
        token: ${{ secrets.GITHUB_TOKEN }}

    # Set up Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    # Install Diesel CLI
    - name: Install Diesel CLI
      run: |
        if ! command -v diesel &> /dev/null
        then
          cargo install diesel_cli --no-default-features --features postgres
        fi

    # Wait for PostgreSQL
    - name: Wait for PostgreSQL
      run: sleep 10s

    # Run Diesel migrations
    - name: Run Diesel migrations
      run: diesel migration run

    # Run Rust tests
    - name: Run Rust tests
      run: cargo test -- --test-threads=1

