name: Rust Tests with Database

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    env:
      DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    # Install Diesel CLI
    - name: Install Diesel CLI
      run: |
        cargo install diesel_cli --no-default-features --features postgres

    # Wait for PostgreSQL to be ready (use sleep or dockerize as previously discussed)
    - name: Wait for PostgreSQL
      run: sleep 10s

    # Run Diesel migrations
    - name: Run Diesel migrations
      run: diesel migration run

    # Run Rust tests
    - name: Run Rust tests
      run: cargo test -- --test-threads=1

