name: Rust Tests with Database

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  test:
    name: Run Rust Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db

    env:
      DATABASE_URL: postgres://test_user:test_password@localhost:5432/test_db

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Print the working directory to check where we are
    - name: Print working directory
      run: pwd

    # List files to check the repository structure
    - name: List files
      run: ls -al

    # Set up Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        profile: minimal

    # Install Diesel CLI
    - name: Install Diesel CLI
      run: |
        if ! command -v diesel &> /dev/null
        then
          cargo install diesel_cli --no-default-features --features postgres
        fi

    # Wait for PostgreSQL
    - name: Wait for PostgreSQL
      run: sleep 10s

    # Conditionally set the working directory based on where we are
    - name: Run Diesel migrations
      run: |
        if [ -f "backend/rust/Cargo.toml" ]; then
          cd backend/rust
        fi
        diesel migration run

    # Run Rust tests, also conditionally set the working directory
    - name: Run Rust tests
      run: |
        if [ -f "backend/rust/Cargo.toml" ]; then
          cd backend/rust
        fi
        cargo test -- --test-threads=1

