name: Trigger Infra Deployment

on:
  tags:
      - 'v*.*.*'

jobs:
  trigger-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Rust Repository
        uses: actions/checkout@v3
        with:
          repository: BlakeDonn/trustystack-rust
          path: backend/rust
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}  


      - name: Trigger Infra Repository Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.INFRA_REPO_PAT }}
          repository: BlakeDonn/trustystack-cicd
          event-type: deploy
